#!/usr/bin/env php
<?php

namespace PhpUnitGen;

use League\Flysystem\Adapter\Local;
use League\Flysystem\Filesystem;
use League\Flysystem\FilesystemInterface;
use PhpUnitGen\Console\Application;
use PhpUnitGen\Container\Container;
use PhpUnitGen\Container\DependencyInjector;
use PhpUnitGen\Container\DependencyInjectorInterface;

$loaded = false;

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        require $file;
        $loaded = true;
        break;
    }
}

if (!$loaded) {
    die(
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
}

$container = new Container();

// Load first dependencies
// And next dependencies will be loaded by PhpUnitGen\Container\DependencyInjector class
$container->setInstance(FilesystemInterface::class, new Filesystem(new Local('./')));
$container->setInstance(DependencyInjectorInterface::class, new DependencyInjector());

// Run application
$application = new Application($container);
$application->run();